'use client';

import { useState } from 'react';
import { Droppable } from '@hello-pangea/dnd';
import { TaskCard } from './task-card';
import { TaskForm } from './task-form';
import { Button } from '@/components/ui/button';
import { Plus, Zap } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { Column as ColumnType } from '@/hooks/use-board';

interface ColumnProps {
  column: ColumnType;
  isAdmin: boolean;
  boardId: number;
  allColumns: ColumnType[];
}

export function Column({ column, isAdmin, boardId, allColumns }: ColumnProps) {
  const [isTaskFormOpen, setIsTaskFormOpen] = useState(false);

  // Sort tasks by order
  const sortedTasks = [...column.tasks].sort((a, b) => a.order - b.order);

  // Get column status color
  const getColumnColor = (name: string) => {
    const lowerName = name.toLowerCase();
    if (lowerName.includes('todo') || lowerName.includes('backlog')) {
      return 'from-gray-500/20 to-gray-600/20 border-gray-500/30';
    }
    if (lowerName.includes('progress') || lowerName.includes('doing')) {
      return 'from-yellow-500/20 to-orange-500/20 border-yellow-500/30';
    }
    if (lowerName.includes('review') || lowerName.includes('testing')) {
      return 'from-blue-500/20 to-purple-500/20 border-blue-500/30';
    }
    if (lowerName.includes('done') || lowerName.includes('complete')) {
      return 'from-green-500/20 to-emerald-500/20 border-green-500/30';
    }
    return 'from-ai-violet-500/20 to-electric-blue-500/20 border-ai-violet-500/30';
  };

  return (
    <>
      <div className="flex flex-col w-80 min-h-[600px] max-w-sm">
        {/* Column Container with Glassmorphism */}
        <div className="glass-subtle rounded-xl p-4 h-full flex flex-col">
          {/* Column Header */}
          <div className="flex items-center justify-between mb-4 pb-3 border-b border-white/10">
            <div className="flex items-center gap-2">
              <div className={cn(
                "w-3 h-3 rounded-full bg-gradient-to-r",
                getColumnColor(column.name)
              )} />
              <h3 className="font-semibold text-foreground tracking-tight text-sm">
                {column.name}
              </h3>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground font-medium px-2 py-1 bg-white/5 rounded-full border border-white/10">
                {sortedTasks.length}
              </span>
              {/* AI indicator for columns with AI-enhanced tasks */}
              {sortedTasks.some(task => task.description?.includes('Generated by AI Task Analyzer')) && (
                <div className="flex items-center gap-1 px-2 py-1 bg-ai-violet-500/20 border border-ai-violet-500/30 rounded-full">
                  <Zap className="w-3 h-3 text-ai-violet-400" />
                  <span className="text-xs text-ai-violet-400 font-medium">AI</span>
                </div>
              )}
            </div>
          </div>

          {/* Droppable Area */}
          <Droppable droppableId={column.id.toString()}>
            {(provided, snapshot) => (
              <div
                ref={provided.innerRef}
                {...provided.droppableProps}
                className={cn(
                  'flex-1 min-h-[400px] space-y-3 rounded-lg p-2 transition-all duration-300 ease-in-out overflow-y-auto column-scroll',
                  snapshot.isDraggingOver
                    ? 'bg-ai-violet-500/10 border-2 border-dashed border-ai-violet-500/50 scale-[1.02]'
                    : 'border-2 border-dashed border-transparent'
                )}
                style={{ maxHeight: 'calc(100vh - 300px)' }}
              >
                {sortedTasks.length === 0 ? (
                  <div className="flex flex-col items-center justify-center h-32 text-muted-foreground text-sm">
                    <div className="w-12 h-12 rounded-full bg-white/5 border border-white/10 flex items-center justify-center mb-2">
                      <Plus className="w-6 h-6" />
                    </div>
                    <span>No tasks yet</span>
                    <span className="text-xs opacity-60">Drop tasks here</span>
                  </div>
                ) : (
                  sortedTasks.map((task, index) => (
                    <div
                      key={task.id}
                      className="animate-fade-in"
                      style={{
                        animationDelay: `${index * 50}ms`,
                        animationFillMode: 'forwards'
                      }}
                    >
                      <TaskCard
                        task={task}
                        index={index}
                        boardId={boardId}
                        columns={allColumns}
                      />
                    </div>
                  ))
                )}
                {provided.placeholder}
              </div>
            )}
          </Droppable>

          {/* Add Task Button (Admin Only) */}
          {isAdmin && (
            <div className="mt-4 pt-3 border-t border-white/10 flex-shrink-0">
              <Button
                variant="ghost"
                size="sm"
                className="w-full justify-start text-muted-foreground hover:text-foreground hover:bg-white/10 border border-transparent hover:border-white/20 rounded-lg transition-all duration-300"
                onClick={() => setIsTaskFormOpen(true)}
              >
                <Plus className="w-4 h-4 mr-2" />
                Add task
              </Button>
            </div>
          )}
        </div>
      </div>

      {/* Task Form Modal */}
      <TaskForm
        boardId={boardId}
        columns={allColumns}
        defaultColumnId={column.id}
        isOpen={isTaskFormOpen}
        onClose={() => setIsTaskFormOpen(false)}
      />
    </>
  );
}