from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from datetime import datetime
from ..core.database import Base


class Comment(Base):
    """
    Comment model for task comments and AI-generated status updates.
    
    Attributes:
        id: Primary key
        content: Comment text content
        is_ai_generated: Boolean flag indicating if comment was generated by AI
        task_id: Foreign key to the Task this comment belongs to
        author_id: Foreign key to User who created the comment (can be null for AI)
        created_at: Timestamp of comment creation
        updated_at: Timestamp of last comment update
        
    Relationships:
        task: Task this comment belongs to (many-to-one)
        author: User who created the comment (many-to-one, optional)
    """
    __tablename__ = "comments"
    
    # Primary key
    id = Column(Integer, primary_key=True, index=True)
    
    # Comment information
    content = Column(Text, nullable=False)
    is_ai_generated = Column(Boolean, default=False, nullable=False)
    
    # Foreign keys
    task_id = Column(Integer, ForeignKey("tasks.id"), nullable=False)
    author_id = Column(Integer, ForeignKey("users.id"), nullable=True)  # Null for AI comments
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    task = relationship("Task", back_populates="comments")
    author = relationship("User", back_populates="comments")
    
    def __repr__(self):
        return f"<Comment(id={self.id}, task_id={self.task_id}, is_ai_generated={self.is_ai_generated})>"