/**
 * AI Task Analyzer Service
 * Integrates with the backend AI endpoints
 */

import { apiClient } from './api';

export interface TaskAnalysis {
  technical_subtasks: string[];
  acceptance_criteria: string[];
  potential_blockers: string[];
  estimated_complexity: 'low' | 'medium' | 'high';
  domain: string;
  confidence_score: number;
}

export interface AnalyzeTaskRequest {
  prompt: string;
  context?: string;
}

export interface AnalyzeTaskResponse {
  success?: boolean;
  analysis?: TaskAnalysis;
  error?: string;
}

class AIAnalyzerService {
  async analyzeTask(request: AnalyzeTaskRequest): Promise<TaskAnalysis> {
    try {
      const response = await apiClient.post('/ai/analyze', request);
      return response.data;
    } catch (error) {
      console.error('AI Analysis failed:', error);
      throw error;
    }
  }

  async enhanceTask(taskId: number, request: AnalyzeTaskRequest): Promise<any> {
    try {
      const response = await apiClient.post(`/ai/enhance-task/${taskId}`, request);
      return response.data;
    } catch (error) {
      console.error('Task enhancement failed:', error);
      throw error;
    }
  }

  async checkHealth(): Promise<boolean> {
    try {
      const response = await apiClient.get('/ai/health');
      return response.data.status === 'healthy';
    } catch {
      return false;
    }
  }

  /**
   * Format analysis results into markdown for task description
   */
  formatAnalysisAsMarkdown(analysis: TaskAnalysis, originalTitle: string): string {
    const markdown = `# ${originalTitle}

## 🎯 AI Analysis Summary
- **Domain**: ${analysis.domain.toUpperCase()}
- **Complexity**: ${analysis.estimated_complexity.toUpperCase()}
- **Confidence**: ${Math.round(analysis.confidence_score * 100)}%

## 📋 Technical Sub-Tasks
${analysis.technical_subtasks.map((task, index) => `${index + 1}. ${task}`).join('\n')}

## ✅ Acceptance Criteria
${analysis.acceptance_criteria.map((criteria, index) => `${index + 1}. ${criteria}`).join('\n')}

## ⚠️ Potential Blockers
${analysis.potential_blockers.map((blocker, index) => `${index + 1}. ${blocker}`).join('\n')}

---
*Generated by AI Task Analyzer*`;

    return markdown;
  }

  /**
   * Create individual sub-tasks from analysis
   */
  createSubTasksData(analysis: TaskAnalysis, parentTask: any, columnId: number): any[] {
    return analysis.technical_subtasks.map((subtask, index) => ({
      title: `${parentTask.title} - ${subtask}`,
      description: `**Sub-task ${index + 1} of ${analysis.technical_subtasks.length}**\n\n${subtask}\n\n**Acceptance Criteria:**\n${analysis.acceptance_criteria[index] || 'Complete the sub-task as described'}`,
      priority: analysis.estimated_complexity === 'high' ? 'high' : 'medium',
      column_id: columnId,
      assignee_id: parentTask.assignee_id,
      due_date: parentTask.due_date,
    }));
  }
}

export const aiAnalyzer = new AIAnalyzerService();